/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.People;

namespace RosSharp.RosBridgeClient.MessageTypes.People
{
    public class People : Message
    {
        public const string RosMessageName = "people_msgs/People";

        public Header header { get; set; }
        public Person[] people { get; set; }

        public People()
        {
            this.header = new Header();
            this.people = new Person[0];
        }

        public People(Header header, Person[] people)
        {
            this.header = header;
            this.people = people;
        }
    }
}
