/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.People;

namespace RosSharp.RosBridgeClient.MessageTypes.People
{
    public class PersonStamped : Message
    {
        public const string RosMessageName = "people_msgs/PersonStamped";

        public Header header { get; set; }
        public Person person { get; set; }

        public PersonStamped()
        {
            this.header = new Header();
            this.person = new Person();
        }

        public PersonStamped(Header header, Person person)
        {
            this.header = header;
            this.person = person;
        }
    }
}
