/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.People
{
    public class Person : Message
    {
        public const string RosMessageName = "people_msgs/Person";

        public string name { get; set; }
        public Point position { get; set; }
        public Point velocity { get; set; }
        public double reliability { get; set; }
        public string[] tagnames { get; set; }
        public string[] tags { get; set; }

        public Person()
        {
            this.name = "";
            this.position = new Point();
            this.velocity = new Point();
            this.reliability = 0.0;
            this.tagnames = new string[0];
            this.tags = new string[0];
        }

        public Person(string name, Point position, Point velocity, double reliability, string[] tagnames, string[] tags)
        {
            this.name = name;
            this.position = position;
            this.velocity = velocity;
            this.reliability = reliability;
            this.tagnames = tagnames;
            this.tags = tags;
        }
    }
}
