/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class BumperEvent : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/BumperEvent";

        //  Provides a bumper event.
        //  This message is generated whenever a particular bumper is pressed or released.
        //  Note that, despite bumper field on SensorState messages, state field is not a
        //  bitmask, but the new state of a single sensor.
        //  bumper
        public const byte LEFT = 0;
        public const byte CENTER = 1;
        public const byte RIGHT = 2;
        //  state
        public const byte RELEASED = 0;
        public const byte PRESSED = 1;
        public byte bumper { get; set; }
        public byte state { get; set; }

        public BumperEvent()
        {
            this.bumper = 0;
            this.state = 0;
        }

        public BumperEvent(byte bumper, byte state)
        {
            this.bumper = bumper;
            this.state = state;
        }
    }
}
