/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class ControllerInfo : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/ControllerInfo";

        //  Controller info message, contains PID parameters
        public const byte DEFAULT = 0;
        public const byte USER_CONFIGURED = 1;
        public byte type { get; set; }
        public double p_gain { get; set; }
        // should be positive
        public double i_gain { get; set; }
        // should be positive
        public double d_gain { get; set; }
        // should be positive

        public ControllerInfo()
        {
            this.type = 0;
            this.p_gain = 0.0;
            this.i_gain = 0.0;
            this.d_gain = 0.0;
        }

        public ControllerInfo(byte type, double p_gain, double i_gain, double d_gain)
        {
            this.type = type;
            this.p_gain = p_gain;
            this.i_gain = i_gain;
            this.d_gain = d_gain;
        }
    }
}
