/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class DigitalInputEvent : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/DigitalInputEvent";

        //  This message is generated whenever the value of one or more digital input pins changes.
        //  Array of values; indices represent pins 0-3 respectively.
        public bool[] values { get; set; }

        public DigitalInputEvent()
        {
            this.values = new bool[4];
        }

        public DigitalInputEvent(bool[] values)
        {
            this.values = values;
        }
    }
}
