/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class DockInfraRed : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/DockInfraRed";

        //  Docking base ir sensors messages.
        //  Generated on the proximity of the docking base to assist the automatic docking.
        public const byte NEAR_LEFT = 1;
        public const byte NEAR_CENTER = 2;
        public const byte NEAR_RIGHT = 4;
        public const byte FAR_LEFT = 16;
        public const byte FAR_CENTER = 8;
        public const byte FAR_RIGHT = 32;
        public Header header { get; set; }
        public byte[] data { get; set; }

        public DockInfraRed()
        {
            this.header = new Header();
            this.data = new byte[0];
        }

        public DockInfraRed(Header header, byte[] data)
        {
            this.header = header;
            this.data = data;
        }
    }
}
