/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class ExternalPower : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/ExternalPower";

        //  Turn on/off Kobuki's external power sources
        //  Power sources
        public const byte PWR_3_3V1A = 0; //  DB25 connector only
        public const byte PWR_5V1A = 1; //  DB25 connector and Micro Molex connector
        public const byte PWR_12V5A = 2; //  Micro Molex connector only
        public const byte PWR_12V1_5A = 3; //  Micro Molex connector only
        //  State
        public const byte OFF = 0;
        public const byte ON = 1;
        public byte source { get; set; }
        public byte state { get; set; }

        public ExternalPower()
        {
            this.source = 0;
            this.state = 0;
        }

        public ExternalPower(byte source, byte state)
        {
            this.source = source;
            this.state = state;
        }
    }
}
