/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class KeyboardInput : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/KeyboardInput";

        //  KEYBOARD INPUT
        //  
        //  Keycodes to be transferred for remote teleops.
        public const byte KeyCode_Right = 67; //  0x43
        public const byte KeyCode_Left = 68; //  0x44
        public const byte KeyCode_Up = 65; //  0x41
        public const byte KeyCode_Down = 66; //  0x42
        public const byte KeyCode_Space = 32; //  0x20
        public const byte KeyCode_Enable = 101; //  0x65, 'e'
        public const byte KeyCode_Disable = 100; //  0x64, 'd'
        public byte pressedKey { get; set; }

        public KeyboardInput()
        {
            this.pressedKey = 0;
        }

        public KeyboardInput(byte pressedKey)
        {
            this.pressedKey = pressedKey;
        }
    }
}
