/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class Led : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/Led";

        //  Sends a command for controlling the a LED.
        //  
        //  Typically the first LED is always reserved to denote
        //  the state - the remainder will be controllable. 
        public const byte BLACK = 0;
        public const byte GREEN = 1;
        public const byte ORANGE = 2;
        public const byte RED = 3;
        //  For kobuki there are only two controllable LED's.
        public byte value { get; set; }

        public Led()
        {
            this.value = 0;
        }

        public Led(byte value)
        {
            this.value = value;
        }
    }
}
