/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class RobotStateEvent : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/RobotStateEvent";

        //  Provides a robot state event
        //  This message is generated whenever the robot gets online/offline
        public const byte ONLINE = 1;
        public const byte OFFLINE = 0;
        public byte state { get; set; }

        public RobotStateEvent()
        {
            this.state = 0;
        }

        public RobotStateEvent(byte state)
        {
            this.state = state;
        }
    }
}
