/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class ScanAngle : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/ScanAngle";

        public Header header { get; set; }
        public double scan_angle { get; set; }

        public ScanAngle()
        {
            this.header = new Header();
            this.scan_angle = 0.0;
        }

        public ScanAngle(Header header, double scan_angle)
        {
            this.header = header;
            this.scan_angle = scan_angle;
        }
    }
}
