/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class Sound : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/Sound";

        //  Sends a command for playing sounds.
        //  The available sound sequences:
        //  0 - turn on
        //  1 - turn off
        //  2 - recharge start
        //  3 - press button,
        //  4 - error sound
        //  5 - start cleaning
        //  6 - cleaning end
        public const byte ON = 0;
        public const byte OFF = 1;
        public const byte RECHARGE = 2;
        public const byte BUTTON = 3;
        public const byte ERROR = 4;
        public const byte CLEANINGSTART = 5;
        public const byte CLEANINGEND = 6;
        public byte value { get; set; }

        public Sound()
        {
            this.value = 0;
        }

        public Sound(byte value)
        {
            this.value = value;
        }
    }
}
