/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class VersionInfo : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/VersionInfo";

        //  Contains unique device id, version info and available features for the kobuki platform.
        //  Useful for compatibility checking and introspection
        public string hardware { get; set; }
        //  <major>.<minor>.<patch>
        public string firmware { get; set; }
        //  <major>.<minor>.<patch>
        public string software { get; set; }
        //  Still to decide how it will look
        public uint[] udid { get; set; }
        //  Bitmask that specifies the available features in the firmware and/or driver
        public ulong features { get; set; }
        //  The following represent the bit fields corresponding to bits in the features value
        //  Provided firmware kobuki_firmware_1.1.1.hex
        public const ulong SMOOTH_MOVE_START = 0000000000000001;
        public const ulong GYROSCOPE_3D_DATA = 0000000000000002;

        public VersionInfo()
        {
            this.hardware = "";
            this.firmware = "";
            this.software = "";
            this.udid = new uint[0];
            this.features = 0;
        }

        public VersionInfo(string hardware, string firmware, string software, uint[] udid, ulong features)
        {
            this.hardware = hardware;
            this.firmware = firmware;
            this.software = software;
            this.udid = udid;
            this.features = features;
        }
    }
}
