/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Kobuki
{
    public class WheelDropEvent : Message
    {
        public const string RosMessageName = "kobuki_msgs-noetic/WheelDropEvent";

        //  Provides a wheel drop event.
        //  This message is generated whenever one of the wheels is dropped (robot fell
        //  or was raised) or raised (normal condition).
        //  Note that, despite wheel_drop field on SensorState messages, state field is
        //  not a bitmask, but the new state of a single sensor.
        //  wheel
        public const byte LEFT = 0;
        public const byte RIGHT = 1;
        //  state
        public const byte RAISED = 0;
        public const byte DROPPED = 1;
        public byte wheel { get; set; }
        public byte state { get; set; }

        public WheelDropEvent()
        {
            this.wheel = 0;
            this.state = 0;
        }

        public WheelDropEvent(byte wheel, byte state)
        {
            this.wheel = wheel;
            this.state = state;
        }
    }
}
