/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.SENSAR
{
    public class SingleColorLED : Message
    {
        public const string RosMessageName = "SENSAR/SingleColorLED";

        public ColorRGBA color { get; set; }
        public double duration { get; set; }
        public sbyte[] leds { get; set; }
        public bool repeating { get; set; }

        public SingleColorLED()
        {
            this.color = new ColorRGBA();
            this.duration = 0.0;
            this.leds = new sbyte[0];
            this.repeating = false;
        }

        public SingleColorLED(ColorRGBA color, double duration, sbyte[] leds, bool repeating)
        {
            this.color = color;
            this.duration = duration;
            this.leds = leds;
            this.repeating = repeating;
        }
    }
}
